#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-ip-qos ) && rm -f /etc/uci-defaults/luci-ip-qos
	chmod 755 /etc/init.d/ip-qos >/dev/null 2>&1
	/etc/init.d/ip-qos enable >/dev/null 2>&1
	exit 0
}
