#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autossh[-1]
	add ucitrack autossh
	set ucitrack.autossh="autossh"
	set ucitrack.autossh.init='autossh'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
