#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org
START=90

config_cb() {
	local cfg="$CONFIG_SECTION"
	config_get configname "$cfg" TYPE

	# check if section is enabled (default)
	local enabled
	config_get_bool enabled "${cfg}" enabled 1
	[ "${enabled}" -eq 0 ] && return 1
	
	case "$configname" in
		edge)
			config_get ipaddr "$cfg" ipaddr
			config_get supernode "$cfg" supernode
			config_get port "$cfg" port
			config_get community "$cfg" community
			config_get mode "$cfg" mode
			config_get key "$cfg" key
			config_get mtu "$cfg" mtu
			config_get_bool route "$cfg" route 0

			
		if [ "$mode" = '0' ];then
			[ "$route" = "1" ] && args='-r'
			if [ "$ipaddr" != "" ]; then
				edge -f $args -a $ipaddr -c $community -k $key -l ${supernode}:${port} -M $mtu
			fi
		else
			args="-l ${supernode}:${port}"
			[ "$supernode2" != "" ] && args="$args -l $(supernode2):${port}"
			[ "$route" = "1" ] && args="$args -r"

			if [ "$ipaddr" != "" ]; then
				N2N_KEY="$key" edge2  $args -a $ipaddr -c $community  -M $mtu
			fi
		fi
		;;
		supernode)
			config_get port "$cfg" port
			if [ "$port" != "" ]; then
				supernode -l $port &
			fi
		;;
		supernode2)
			config_get port "$cfg" port
			if [ "$port" != "" ]; then
				supernode2 -l $port &
			fi
		;;
	esac
}

start() {
	config_load n2n
}

stop() {
	service_stop /sbin/edge
	service_stop /sbin/supernode
	service_stop /sbin/edge2
	service_stop /sbin/supernode2
}

restart() {
	stop
	start
}
