#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-shadowsocks ) && rm -f /etc/uci-defaults/luci-youku
	chmod 755 /etc/init.d/youku >/dev/null 2>&1
	/etc/init.d/youku enable >/dev/null 2>&1
	exit 0
}
