#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
. /lib/functions.sh
START=19

pppoe_name=$(uci get network.wan.username) 
pppoe_pw=$(uci get network.wan.password)
#pppoe_metric=$(uci get network.wan.metric) 
wannum=$(uci get macvlan.config.wannum)
ENABLED=$(uci get macvlan.config.enabled)
genrmcfg() {
	echo '#!/bin/sh' >> /tmp/rmcfg.sh
	echo 'uci set multiwan.config.enabled=0' >> /tmp/rmcfg.sh
	for i in $(seq 1 $wannum)
	do
		echo "uci del network.vwan${i}
uci del dhcp.vth${i}
uci del_list firewall.@zone[1].network=vwan${i}
uci del multiwan.vwan${i}
ip link delete vth${i} type macvlan" >> /tmp/rmcfg.sh
	done
	echo "uci commit " >> /tmp/rmcfg.sh
	chmod +x /tmp/rmcfg.sh	
}


start() {
	[ -f /etc/config/macvlan ] || {
		echo "You are missing configuration file /etc/config/macvlan"
		return 1
	}
#	echo -1 > /proc/sys/net/ipv4/rt_cache_rebuild_count
	config_load "macvlan"

	config_get ENABLED config enabled

	[ "$ENABLED" == "0" ] && {
		echo "MACVLAN is disabled."
		return 1
	}

	config_get PORTNUM config wannum
	ifname=$(uci get network.wan.ifname)
	for i in $(seq 1 $PORTNUM)
	do
		ip link add link $ifname vth$i type macvlan
		ifconfig vth$i hw ether $(echo $(cat /sys/class/net/$ifname/address|awk -F ":" '{print $1":"$2":"$3":"$4":"$5":" }')$(echo "" | awk -F ":" '{printf("%X\n", 16+i);}' i=$i))
		ifconfig vth$i up
	done
	genrmcfg

}

stop() {
	echo "Nothing to do"
}
