#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-autossh ) && rm -f /etc/uci-defaults/luci-autossh
	chmod 755 /etc/init.d/autossh >/dev/null 2>&1
	/etc/init.d/autossh enable >/dev/null 2>&1
	exit 0
}
