#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@usbttl[-1]
	add ucitrack usbttl
	set ucitrack.usbttl="usbttl"
	set ucitrack.usbttl.init='usbttl'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
